# Generated by Django 4.1.3 on 2023-01-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_authors_author_rename_books_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_picture',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
