# Generated by Django 4.1.3 on 2023-01-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_book_cover_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_picture',
            field=models.ImageField(default='nothing', null=True, upload_to=''),
        ),
    ]
