# Generated by Django 4.1.3 on 2023-01-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_book_completeness_alter_book_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(blank=True, default=2015, null=True),
        ),
    ]
