# Generated by Django 4.1.3 on 2023-01-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_picture',
            field=models.FileField(upload_to=''),
        ),
    ]
