# Generated by Django 4.1.3 on 2023-01-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_book_cover_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover_picture',
            new_name='dir_name',
        ),
    ]
