# Generated by Django 4.1.3 on 2023-01-27 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_rename_cover_picture_book_dir_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='dir_name',
            new_name='cover_picture',
        ),
    ]
