# Generated by Django 4.1.3 on 2023-01-31 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_book_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 17, 5, 50, 65908, tzinfo=datetime.timezone.utc)),
        ),
    ]
