# Generated by Django 4.1.3 on 2023-01-31 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_alter_book_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='likes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
